# Generated by Django 6.0.5 on 2026-05-22 07:41

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('CHEQUE', 'Cancelled Cheque'), ('MSME', 'MSME Certificate')], max_length=10)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboarding')),
            ],
            options={
                'db_table': 'documents',
                'unique_together': {('onboarding', 'document_type')},
            },
        ),
    ]
