# Generated by Django 6.0.5 on 2026-07-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extracted_data_document_scanned_at'),
        ('onboarding', '0022_onboarding_pan_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('CHEQUE', 'Cancelled Cheque'), ('MSME', 'MSME Certificate'), ('OTHER', 'Additional Document')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'OTHER'), _negated=True), fields=('onboarding', 'document_type'), name='unique_single_slot_document_type'),
        ),
    ]
