# Generated by Django 6.0.5 on 2026-05-22 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('onboarding_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('emails', models.JSONField(default=list)),
                ('phones', models.JSONField(default=list)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(default='India', max_length=100)),
                ('street1', models.CharField(blank=True, max_length=35)),
                ('street2', models.CharField(blank=True, max_length=40)),
                ('street3', models.CharField(blank=True, max_length=40)),
                ('street4', models.CharField(blank=True, max_length=40)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('account_holder_name', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('account_type', models.CharField(blank=True, choices=[('Current', 'Current'), ('Savings', 'Savings'), ('OD', 'OD/CC')], max_length=10)),
                ('msme_applicable', models.BooleanField(default=False)),
                ('msme_status', models.CharField(default='MNA', max_length=20)),
                ('msme_category', models.CharField(blank=True, max_length=10)),
                ('udyam_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_onboardings', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_onboardings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_onboardings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboardings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expiry', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='onboarding.onboarding')),
            ],
            options={
                'db_table': 'onboarding_tokens',
            },
        ),
    ]
