from django.db import migrations, models


PURCHASE_ORGANIZATIONS = [
    ('R001', 'RADICO KHAITAN LTD-HO'),
    ('C001', 'CITROCK'),
    ('I001', 'IBD PUR.ORG.'),
    ('PM01', 'MPL PUR.ORG.'),
    ('PM02', 'WB PUR.ORG.'),
    ('PM03', 'ASSAM PUR.ORG.'),
    ('PM04', 'T.G PUR ORG'),
    ('PM05', 'PUR.ORG. ASSAM'),
    ('PM06', 'PUR.ORG. ODISA'),
    ('PM07', 'PUR.ORG. UP'),
    ('PM08', 'PUR.ORG. MEGHALAYA'),
    ('PM09', 'PUR.ORG. SIKKIM'),
    ('PM10', 'PUR.ORG. RANCHI'),
    ('PM11', 'PUR.ORG. HY'),
    ('PM12', 'PUR.ORG. TN'),
    ('PM13', 'PUR.ORG. MIZORAM'),
    ('PM14', 'PUR.ORG. KAR'),
    ('PM15', 'PUR.ORG. AP'),
    ('PM16', 'PUR.ORG. JHARKHAND'),
    ('PM17', 'PUR.ORG. PUNJAB'),
    ('PM18', 'PUR.ORG. HP'),
    ('PM19', 'PUR.ORG. HR'),
    ('PM20', 'PUR.ORG. KK'),
    ('PM21', 'PUR.ORG. UT'),
    ('PM22', 'PUR.ORG. KERALA'),
    ('PM23', 'PUR.ORG. MP'),
    ('PM24', 'PUR.ORG. AP'),
    ('PM25', 'PUR.ORG. AF'),
    ('PM26', 'PUR.ORG. AR'),
    ('H001', 'MHL PUR.ORG.'),
    ('F002', 'PB PUR.ORG.'),
    ('F003', 'HP PUR.ORG.'),
    ('R002', 'EXPORTS RAMPUR'),
    ('R003', 'RADICO KHAITAN LIMITED, RAMPUR'),
    ('R004', 'CNO RAMPUR'),
    ('R005', 'CIL RAMPUR'),
    ('R006', 'CIL MYSORE UNIT'),
    ('R007', 'ALL INDIA RURAL MARKET'),
    ('R008', 'RAMPUR GRAIN PLANT'),
    ('R009', 'RAMPUR PRINTING PLANT'),
    ('R010', 'MALT PLANT RAMPUR'),
    ('R015', 'RADICO TIMARPUR'),
    ('R016', 'PRINTING UNIT BAHADURGARH'),
    ('R017', 'DROPL'),
    ('R020', 'P-12 PLANT'),
    ('R021', 'RAMPUR BOTTLING PLANT'),
    ('R022', 'RADICO POISONS'),
    ('R023', 'RADICO KHAITAN TQ-BATCHII'),
    ('R024', 'RADICO KHAITAN TN-HYDER'),
    ('R025', 'RADICO KHAITAN LTD-MPL'),
    ('R026', 'MK MANSION INDORE'),
    ('R027', 'RKL MEGHALAYA'),
    ('R028', 'RKL UNITED DISTILLERS'),
    ('R029', 'RKL RANA SUGARS LIMITED'),
    ('R030', 'RKL GWALIOR AIRPORT PVT LTD'),
    ('R031', 'RKL SENTINI BIOPRODUCTS PVT LTD'),
    ('R032', 'RKL-DEK SPIRITS'),
    ('R033', 'RADICO KHAITAN LTD-HY'),
    ('R034', 'RADICO KHAITAN LTD-HP'),
    ('R035', 'RADICO KHAITAN LTD KOLKATA'),
    ('R036', 'RAMPUR ONE PLANT'),
    ('R037', 'CNO PRINTING UNIT BAHADURGARH'),
    ('R039', 'RADICO KHAITAN TQ-II BREWERIES'),
    ('R040', 'RKL-Mohan Breweries and Distilleries Ltd'),
    ('R041', 'RKL-UDVIL DISTILLERIES'),
    ('R042', 'RKL-MHK DISTILLATIONS PVT LTD'),
    ('R043', 'RADICO NV EXPORT PLANT'),
    ('R044', 'RADICO KHAITAN LIMITED SOLAN'),
    ('R045', 'RKL-RDH AGRO VENTURES PVT LTD'),
    ('R046', 'RADICO KHAITAN TQ-II PLANT'),
    ('R047', 'CNO SPIRITZON PLANT WB'),
    ('R049', 'CNO SPIRITZON PLANT TELANGANA'),
    ('R051', 'CNO SENTINI AP PLANT RAMPUR'),
    ('R052', 'Senti Transverse Distilleries'),
    ('R053', 'Kalady'),
    ('R054', 'Suntory-Osaka'),
    ('R055', 'MPL DISTILLERIES'),
    ('R056', 'Global bottlers'),
    ('R057', 'WODC-CBE'),
    ('R058', 'KAIS DISTILLERIES'),
    ('R059', 'BRAWN WINES'),
    ('R060', 'Talwandi Sabo'),
    ('R061', 'PET ORG-RET TG'),
    ('R062', 'Printing unit AURANG'),
    ('R063', 'SILAPUR PUR ORG'),
    ('R064', 'RKL SSP PUR ORG'),
    ('R065', 'RKL SIFAR PUR ORG'),
    ('R066', 'RKL MMH'),
    ('R067', 'RKL PBR'),
    ('R068', 'RKL PRAGATI'),
    ('R069', 'RKL-GREAT GALLEON'),
    ('R070', 'RKL-GLEN DIST.'),
    ('R071', 'RKL FLAM'),
    ('R072', 'RKL EVEREADY'),
    ('R073', 'RKL BHATIA WINES'),
    ('R074', 'RKL CAPROCOR'),
    ('R100', 'SITAPUR OPERATIONS'),
    ('R101', 'RKL-GREENFIELD DIST.'),
]


def seed_purchase_organizations(apps, schema_editor):
    PurchaseOrganizationMaster = apps.get_model('onboarding', 'PurchaseOrganizationMaster')
    for purchase_organization, description in PURCHASE_ORGANIZATIONS:
        PurchaseOrganizationMaster.objects.update_or_create(
            purchase_organization=purchase_organization,
            defaults={'description': description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_payment_term_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrganizationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_organization', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_organization_masters',
                'ordering': ['purchase_organization'],
            },
        ),
        migrations.RunPython(seed_purchase_organizations, migrations.RunPython.noop),
    ]
