# Generated by Django 4.2.13 on 2026-06-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_search_term_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
