# Generated by Django 4.2.13 on 2026-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0012_onboarding_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='pan_verification_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pan_verification_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='pan_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
