# Generated by Django 4.2.13 on 2026-06-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_onboarding_pan_verification_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='gst_verification_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='gst_verification_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='gst_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='gst_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
