# Generated by Django 6.0.5 on 2026-07-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0021_boss_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='pan_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
