# Generated by Django 6.0.5 on 2026-07-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0022_onboarding_pan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='distribution_channel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='division',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='sales_organization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
