# Generated by Django 6.0.5 on 2026-07-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0023_onboarding_distribution_channel_onboarding_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionChannelMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_channel', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'distribution_channel_masters',
                'ordering': ['distribution_channel'],
            },
        ),
        migrations.CreateModel(
            name='DivisionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'division_masters',
                'ordering': ['division'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrganizationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_organization', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_organization_masters',
                'ordering': ['sales_organization'],
            },
        ),
    ]
