# Generated by Django 6.0.5 on 2026-07-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0024_distributionchannelmaster_divisionmaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCompanyCodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_company_code_masters',
                'ordering': ['company_code'],
            },
        ),
        migrations.CreateModel(
            name='TransportationZoneMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transportation_zone_masters',
                'ordering': ['zone'],
            },
        ),
        migrations.AddField(
            model_name='onboarding',
            name='customer_company_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='transportation_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
