# Generated by Django 6.0.5 on 2026-07-14 07:40

from django.db import migrations, models


def clear_sales_organization(apps, schema_editor):
    Onboarding = apps.get_model('onboarding', 'Onboarding')
    Onboarding.objects.update(sales_organization='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0025_customercompanycodemaster_transportationzonemaster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSearchTermMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=50, unique=True)),
                ('applicable_for', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_search_term_masters',
                'ordering': ['search_term'],
            },
        ),
        migrations.AddField(
            model_name='onboarding',
            name='customer_search_term',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='sales_reference_orgs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(clear_sales_organization, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='onboarding',
            name='sales_organization',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
