# Generated by Django 6.0.5 on 2026-07-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0026_customersearchtermmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
