# Generated by Django 6.0.5 on 2026-07-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0027_widen_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPlantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=20, unique=True)),
                ('plant_name', models.CharField(max_length=255)),
                ('sales_organization', models.CharField(blank=True, max_length=20)),
                ('distribution_channel', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'delivery_plant_masters',
                'ordering': ['plant'],
            },
        ),
        migrations.AddField(
            model_name='onboarding',
            name='delivery_plant',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
