# Generated by Django 6.0.5 on 2026-07-20 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0028_deliveryplantmaster_onboarding_delivery_plant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingapprovalhistory',
            name='onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='onboarding.onboarding'),
        ),
        migrations.CreateModel(
            name='ExtensionEditRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('EXTENSION', 'Extension'), ('EDIT', 'Edit')], max_length=10)),
                ('target_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], max_length=10)),
                ('account_number', models.CharField(max_length=34)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('remarks_request', models.TextField(blank=True)),
                ('reference_purchase_orgs', models.JSONField(blank=True, default=list)),
                ('purchase_orgs_to_open', models.CharField(blank=True, max_length=50)),
                ('search_term', models.CharField(blank=True, max_length=50)),
                ('company_code_to_open', models.CharField(blank=True, max_length=20)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('tds_codes', models.CharField(blank=True, max_length=255)),
                ('sales_reference_orgs', models.JSONField(blank=True, default=list)),
                ('customer_search_term', models.CharField(blank=True, max_length=50)),
                ('sales_organization', models.JSONField(blank=True, default=list)),
                ('distribution_channel', models.CharField(blank=True, max_length=50)),
                ('division', models.CharField(blank=True, max_length=50)),
                ('delivery_plant', models.CharField(blank=True, max_length=20)),
                ('transportation_zone', models.CharField(blank=True, max_length=50)),
                ('customer_company_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PENDING_BOSS_APPROVAL', 'Pending Boss Approval'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=25)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extension_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_extension_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_extension_edit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extension_edit_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='onboardingapprovalhistory',
            name='extension_edit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='onboarding.extensioneditrequest'),
        ),
        migrations.AddConstraint(
            model_name='onboardingapprovalhistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('extension_edit_request__isnull', True), ('onboarding__isnull', False)), models.Q(('extension_edit_request__isnull', False), ('onboarding__isnull', True)), _connector='OR'), name='approval_history_exactly_one_target'),
        ),
    ]
