# Generated by Django 6.0.5 on 2026-07-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0029_alter_onboardingapprovalhistory_onboarding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensioneditrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='gl_account_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='gl_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='reference_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='reference_vendor_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='vendor_reference_range',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
