# Generated by Django 6.0.5 on 2026-07-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0030_extensioneditrequest_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensioneditrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
