# Generated by Django 6.0.5 on 2026-07-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0031_alter_extensioneditrequest_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensioneditrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
