# Generated by Django 6.0.5 on 2026-07-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0033_fix_tds_higher_rate_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensioneditrequest',
            name='company_name_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='company_name_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='extensioneditrequest',
            name='company_name_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='company_name_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='company_name_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='onboarding',
            name='company_name_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='extensioneditrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='company_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
